[package]
name = "csv_repro"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
#async-channel = "2.3"
csv = "1.3"
tokio = { version="1.38", features = ["rt-multi-thread", "sync", "rt", "macros", "time"] }
futures-util = "0.3"
